//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeManagementApp.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public partial class Task
    {
        public int Id { get; set; }
        [Required]
        public string TaskName { get; set; }
        [Required]
        public string Description { get; set; }

        [DataType(DataType.Date)]
        public System.DateTime StartTime { get; set; }

        [DataType(DataType.Date)]
        public Nullable<System.DateTime> EndTime { get; set; }
        [Required]
        public string Priority { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
